USE bookstore_db;
GO

SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER ON;
SET NUMERIC_ROUNDABORT OFF;
GO

IF EXISTS (
  SELECT 1
  FROM sys.columns
  WHERE object_id = OBJECT_ID(N'refresh_tokens')
    AND name = N'token'
)
BEGIN
  ALTER TABLE refresh_tokens ALTER COLUMN token NVARCHAR(1000) NOT NULL;
END
GO
